### ISSUE TITLE
Show Badge on Card of Issues Having Bonus

### ISSUE THREAD

**Issue by hackko-20** [ContriHUB/ContriHUB-22#33]
Mentors have bonus points (a +5 label with bonus description) for some issues that show it as a badge on the top-left side of the issue cards

This issue is currently assigned to @dhanrajchaurasia.

**Comment by dhanrajchaurasia** [comment]
So do I have to make the cards as follows?
![image](https://user-images.githubusercontent.com/81418590/195970555-aeffc2eb-377b-4beb-9eb0-31b7e4e688c9.png)

**Comment by dhanrajchaurasia** [comment]
Added the "Bonus Badge"

[Pull Request](https://github.com/ContriHUB/ContriHUB-22/pull/105)

**Comment by dhanrajchaurasia** [comment]
@hackko-20 can you merge the PR now?
