### ISSUE TITLE
Check Valid LinkedIn Profile Link

### ISSUE THREAD

**Issue by DuP-491** [ContriHUB/ContriHUB-22#53]
Check whether given input linkedin profile is valid or not.
Validity must be checked both on frontend and backend.
Use of regex is encouraged.

This issue is currently assigned to @Umang1103

**Comment by WaniAthar** [comment]
can i work on this issue? @DuP-491

**Comment by DuP-491** [comment]
@WaniAthar this issue is part of a competition of a college fest
